//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pract.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int roleId { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public bool isBlocked { get; set; }
        public int loginAttempts { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
